### ISSUE TITLE
env_canada not working when configured in French

### ISSUE THREAD

**Issue by mdallaire** [MrBartusek/MeteoalarmCard#100]
### Describe the bug

I am trying to configure the card with Environment Canada but I get the following error:

```
Error: Selected integration doesn't match selected entities: sensor.envcan_statements, sensor.envcan_warnings, sensor.envcan_watches.
```
Those sensors exist and have the valid information from the integration.

### Screenshots

![image](https://user-images.githubusercontent.com/23340663/179754586-7d3642b6-92cf-47e0-93d9-947161a30829.png)
![image](https://user-images.githubusercontent.com/23340663/179754846-fc61ade7-85d8-42b8-b1a3-69ac1eaacd74.png)
![image](https://user-images.githubusercontent.com/23340663/179755085-afeb46f2-21a1-4257-a838-38827644435e.png)
![image](https://user-images.githubusercontent.com/23340663/179755313-425a3a4d-48f3-49b9-a2b5-a94263b94f84.png)

### Card version

v2.0.0

### Integration type

Environnement Canada

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

```yaml
name: Meteoalarm
type: custom:meteoalarm-card
integration: env_canada
entities:
  - entity: sensor.envcan_statements
  - entity: sensor.envcan_warnings
  - entity: sensor.envcan_watches
```

### Integration Configuration

```yaml
No yaml configuration, configured in the integrations
```
![image](https://user-images.githubusercontent.com/23340663/179755644-92096610-ef3f-48b7-8f5a-840a38bcac8a.png)
