### ISSUE TITLE
language does not match the settings

### ISSUE THREAD

**Issue by andybali** [MrBartusek/MeteoalarmCard#101]
### Describe the bug

Shown Language does not match the settings and is not is not identical on different devices and programs/apps.
Original language in the entity is german and is translated to english by the card, although the user's language setting is german.
When opening the page, the text is displayed very briefly in German and then changes to English. Other cards from my interface with automatic text are displayed in german
When opening the page in the browser on the PC, the problem does not occur, it remains in German.

### Screenshots
Language settings:
![LanguageSettingUser Screenshot 2022-07-20 073932](https://user-images.githubusercontent.com/26953186/179907605-57921225-4111-46ad-bdfd-ce9c7cb8a182.jpg)
Orgin entity text:
![entity2022-07-20 07_44_45-Clipboard](https://user-images.githubusercontent.com/26953186/179907628-279e4ab4-1b1f-4308-a07d-98e84ae9c67b.jpg)
Browser Chrome on PC:
![Browser Chrome Screenshot 2022-07-20 073517](https://user-images.githubusercontent.com/26953186/179907641-34a4c698-898a-42ea-89e8-29db39364cd6.jpg)
FullyKioskBrowser on Tablet
![FullykioskBrowser Tablet Screenshot 2022-07-20 073705](https://user-images.githubusercontent.com/26953186/179907672-f3a6c134-a1b7-4ea4-943c-191cd21f2912.jpg)
Smartphone CompanionApp:
![Smartphone CompanionApp_20220720_073802](https://user-images.githubusercontent.com/26953186/179907702-908f4cd7-55b7-4feb-9f7b-9863a72d7a7e.jpg)

### Card version

v2.0.0.0

### Integration type

Deutscher Wetterdienst (DWD)

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

```yaml
type: custom:meteoalarm-card
integration: dwd
entities:
  - entity: sensor.wetterwarnungdwd_xxx_current_warning_level
  - entity: sensor.wetterwarnungdwd_xxx_advance_warning_level
disable_swiper: false
hide_caption: false
```

### Integration Configuration

```yaml
[PASTE CONFIGURATION HERE]
```
