### ISSUE TITLE
Unknown Env canada alert type: Severe Thunderstorms

### ISSUE THREAD

**Issue by Woodcat64** [MrBartusek/MeteoalarmCard#103]
### Describe the bug

Card will not display warnings.
Card will work if  ```  - entity: sensor.watches``` is removed

edit: now we have more warnings and card doesn't work even with watches entity removed
- Severe thunderstorm warning
- Heat warning
and
- Severe thunderstorm watch

### Screenshots

![image](https://user-images.githubusercontent.com/50119854/180092229-c395d1b8-c214-4be9-ba23-6817a16be752.png)
![image](https://user-images.githubusercontent.com/50119854/180092429-9d703a84-bb9e-4553-9feb-101d3e5ae3e3.png)
![image](https://user-images.githubusercontent.com/50119854/180106101-b0baa901-3c60-4237-8e9d-53aaff47ad81.png)

### Card version

v2.0.0

### Integration type

Meteoalarm

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

```yaml
type: custom:meteoalarm-card
entity: update.home_assistant_supervisor_update
integration: env_canada
entities:
  - entity: sensor.warnings
  - entity: sensor.watches
  - entity: sensor.statements
hide_when_no_warning: false
```

### Integration Configuration

```yaml
Configured by HACS
```
