### ISSUE TITLE
Error with Environment Canada Unknown Alert Type

### ISSUE THREAD

**Issue by xthursdayx** [MrBartusek/MeteoalarmCard#118]
### Describe the bug

It seems that this card is not working with all of the Environment Canada alerts. Today, I have a Severe Thunderstorm alert, but the card shows `Error: Unknown Env canada alert type: Severe Thunderstorm`

### Card version

v2.1.0

### Integration type

Environnement Canada

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

```yaml
type: custom:meteoalarm-card
entity: update.home_assistant_supervisor_update
integration: env_canada
entities:
  - entity: sensor.toronto_watches
  - entity: sensor.toronto_warnings
  - entity: sensor.toronto_statements
hide_when_no_warning: true

```

### Integration Configuration

N/A added the the WebUI, not YAML.
