### ISSUE TITLE
Headline is always overwritten

### ISSUE THREAD

**Issue by Volarn** [MrBartusek/MeteoalarmCard#123]
### Describe the bug

Hi there,

i use the Meteoalarm Card in German with Nina integration. At the Moment we have a warning (Thunderstorm) and the App show a orange card with the output 'Orange Warnung'. When Reloading the Overview you kan see shortly the korrekt Warning then cames the 'Orange Warning.

When i tab the warning and then open the Attributes following Headline is there: Amtliche WARNUNG vor STARKEM GEWITTER

What is there wrong?

### Card version

v2.2.0

### Integration type

NINA

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

```yaml
type: custom:meteoalarm-card
integration: nina
entities:
  - entity: binary_sensor.warning_uetersen_stadt_pinneberg_schleswig_holstein_1
  - entity: binary_sensor.warning_uetersen_stadt_pinneberg_schleswig_holstein_2
  - entity: binary_sensor.warning_uetersen_stadt_pinneberg_schleswig_holstein_3
  - entity: binary_sensor.warning_uetersen_stadt_pinneberg_schleswig_holstein_4
  - entity: binary_sensor.warning_uetersen_stadt_pinneberg_schleswig_holstein_5
override_headline: false
```

### Integration Configuration

```yaml
there in nothing in the configuration.yaml
```
