### ISSUE TITLE
'Tornado Watch' shows 'Tornado Warning' on the alarm card

### ISSUE THREAD

**Issue by drpeppershaker** [MrBartusek/MeteoalarmCard#144]
### Describe the bug

Currently experiencing a Tornado Watch in my area, but the alarm card shows a 'Tornado Warning'.

### Steps to reproduce

Set up meteoalarm card with weather alerts integration. Wait for tornado watch from NWS...

### Screenshots

<img width="507" alt="Screen Shot 2023-01-12 at 2 20 47 PM" src="https://user-images.githubusercontent.com/67330126/212161592-ebafd720-c575-453e-9d2e-bea9a94ea880.png">

<img width="599" alt="Screen Shot 2023-01-12 at 2 22 04 PM" src="https://user-images.githubusercontent.com/67330126/212161622-9b0a651c-6304-48fb-8551-62ac6cacda69.png">

### Card version

v2.4.1

### Integration type

Meteoalarm

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

```yaml
type: custom:meteoalarm-card
entities:
  - entity: sensor.weatheralerts_1
integration: weatheralerts

```

### Integration Configuration

**weatheralerts.yaml:**

```yaml
## sensor ##

sensor:
  - platform: weatheralerts
    ## Set (required) 'state' to your 2 character state or zone abbreviation
    ## Set (required) 'zone' to your zone number for the zone feed you want to use
    ## Uncomment and set (optional) 'county' to your county number for the county feed you want to use
    ## The scan_interval is the length of time (in seconds) between alert feed checks (default is 30 seconds)
    state: GA
    zone: 53
    county: 53
    scan_interval: 30

```

NOTE:
I'm using the yaml package from weather alerts:
https://github.com/custom-components/weatheralerts/tree/a2e08c94d4ba92a22f4a6e9ed80ad127ab2db5cd/packages
