### ISSUE TITLE
button wont resize to square? | no name/status when 'off'

### ISSUE THREAD

**Issue by Mariusthvdb** [MrBartusek/MeteoalarmCard#157]
### Describe the bug

or, like custom:button-card, use aspect ratio: 1/1 when in a grid (which should default to `square: true`)

<img width="525" alt="Scherm­afbeelding 2023-02-13 om 17 12 23" src="https://user-images.githubusercontent.com/33354141/218511692-76ce149d-409f-4016-ae29-ca77398ab152.png">

also, with the default config like below, there is no caption/headline at all, would be nice if it said so, like the KNMI integration does 

<img width="455" alt="Scherm­afbeelding 2023-02-13 om 17 16 04" src="https://user-images.githubusercontent.com/33354141/218512206-abae9c94-59f6-4dc6-8346-9169fddb9a4f.png">

and show Green, not black/transparent

color would be even more required on a full scale card:

<img width="534" alt="Scherm­afbeelding 2023-02-13 om 17 25 37" src="https://user-images.githubusercontent.com/33354141/218514624-bef6a792-b3d1-489e-b518-77ec42df85da.png">

Aware we can set it to Not show when 'off', but personally I love the positive feedback, and be sure there is no alert.

### Steps to reproduce

see yaml below, not much more to do

### Card version

v2.4.2

### Integration type

Meteoalarm

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

```yaml
 - type: grid
    columns: 4
    cards:

      - !include /config/dashboard/includes/button/include_button_animated_weather.yaml

      - !include /config/dashboard/includes/button/include_button_wind_direction.yaml

      - !include /config/dashboard/includes/button/include_button_knmi_waarschuwing.yaml

      - type: custom:meteoalarm-card
        integration: meteoalarm
        entities: binary_sensor.meteoalarm_brabant
#         override_headline: false
#         hide_when_no_warning: true

```

### Integration Configuration

```yaml
```
No Yaml, just the Meteoalarm integration setup in the UI for Noord-Brabant (NL)
