### ISSUE TITLE
add action

### ISSUE THREAD

**Issue by Mariusthvdb** [MrBartusek/MeteoalarmCard#158]
**Is your feature request related to a problem? Please describe.**

I can not configure tap/hold like the HA defaults

**Describe the solution you'd like**

would love to be able to do:
```
  - type: custom:meteoalarm-card
    entities: binary_sensor.meteoalarm_brabant
    integration: meteoalarm
    hold_action:
      action: url
      url_path: 'https://www.meteoalarm.org/nl/region/NL'
```

and hold to see the meteoalarm resource directly

**Additional context**

thanks for considering!

**Comment by MrBartusek** [comment]
I just checked it on my phone and hold actions work as expected with the provided configuration

**Comment by Mariusthvdb** [comment]
really sorry to have to get back here, as 

```
  - type: custom:meteoalarm-card
    integration: meteoalarm
    entities: binary_sensor.meteoalarm_brabant
    scaling_mode: headline
    override_headline: false
    hide_when_no_warning: true
    hold_action:
      action: url
      url_path: 'https://www.meteoalarm.org/nl/region/NL'
```

does Not open a browser on hold to navigate to that url. It simply opens the more info.
as fas as I can see I made no mistake, according to the[ Action](https://www.home-assistant.io/dashboards/actions/#hold-action) documentation 
I did check 3 main browsers, so that is not it.

Also, because you mentioned your phone, I also checked the iPhone ios app, and that does not even do anything on hold, and does not show the hold circle to indicate a hold action was initiated. can only click on iPhone.
