### ISSUE TITLE
Color bug in v2.4.3

### ISSUE THREAD

**Issue by 1doubleDD1** [MrBartusek/MeteoalarmCard#163]
### Describe the bug

Hi,
I've just tried your custom card for the first time, and I've downloaded the latest version (v2.4.3).
There seems to be a bug with the coloring in it, as in my region I currently have a moderate yellow warning but the custom card is actually orange, and even if I override headline it says "Orange warning".
Then I downloaded the previous version (v2.4.2) and everything is working OK (color on screen is yellow and override gives me a "Yellow warning")

Again, I've changed nothing except the version od the card.

### Screenshots

![image](https://user-images.githubusercontent.com/99353012/224016912-dd2410e2-5a11-4e6f-ac61-98b442d21ed4.png)
![image](https://user-images.githubusercontent.com/99353012/224016957-0c65f995-bfe6-49d1-a977-8b3a549945ef.png)
![image](https://user-images.githubusercontent.com/99353012/224016989-a7b5b98a-e165-4892-bf5e-8ea914de6e73.png)
![image](https://user-images.githubusercontent.com/99353012/224017016-23430b79-9a35-43cf-9c1a-633f2de569f0.png)
![image](https://user-images.githubusercontent.com/99353012/224017162-5bc86fff-e44b-4dc4-9b50-4a9ebb84c624.png)

### Card version

v2.4.3

### Integration type

Meteoalarm

### Installation type

Manual

### Card Configuration

```yaml
[type: custom:meteoalarm-card
entities:
  - entity: binary_sensor.meteoalarm
integration: meteoalarm
override_headline: false
hide_when_no_warning: true
]
```

### Integration Configuration

```yaml
[binary_sensor:
  - platform: meteoalarm
    country: "Switzerland"
    province: "Effretikon"]
```
