### ISSUE TITLE
Card becomes full height when used in a layout-card grid-view

### ISSUE THREAD

**Issue by Aasikki** [MrBartusek/MeteoalarmCard#164]
### Describe the bug

I have a grid-view for my smart mirror, and when I add this card to the grid, it occupies the same height as the longest card in the view. If I copy this same card to a regular home assistant view, it works as normal.

### Steps to reproduce

1. Create a grid-view layout with layout-card, that has at least two columns
2. Add some card to one column using vertical-stack card
3. Add MeteoalarmCard to another column

### Screenshots

![image](https://user-images.githubusercontent.com/58399890/224474966-a816d605-c03a-4381-a7f5-cca221fcdf43.png)

### Card version

2.4.3

### Integration type

Meteoalarm

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

```yaml
type: custom:meteoalarm-card
entities:
  entity: binary_sensor.meteoalarm_2
integration: meteoalarm
```

### Integration Configuration

-

**Comment by Aasikki** [comment]
Found a workaround, which is to add this css with card-mod, not sure if it messes up when there are multiple alerts though, but works fine with one.

```
style: |
  :host {
    flex: 0 !important;
  }
```

**Comment by MrBartusek** [comment]
Hey, sorry for the late reply! Can you provide the YAML for the layout-card config that causes issues and the expected outcome? I've trouble understanding what is really a problem here.

**Comment by parislyon** [comment]
![Screenshot from 2023-03-29 09-38-25](https://user-images.githubusercontent.com/16954477/228461070-c2871530-5901-4964-aa1b-31db4412e992.png)
![Screenshot from 2023-03-29 09-37-30](https://user-images.githubusercontent.com/16954477/228461071-85c0082d-5466-438d-8c01-1ae930fe00aa.png)
The way I understand it the alert card does not auto scale its height based on the other cards in the gridcard
so either it is too big or too small

I have no coding experience so no solutions from my end

**Comment by Aasikki** [comment]
> Hey, sorry for the late reply! Can you provide the YAML for the layout-card config that causes issues and the expected outcome? I've trouble understanding what is really a problem here.

I made a simplified version of my setup with a few example cards. It needs the [layout card](https://github.com/thomasloven/lovelace-layout-card) to be installed to work.

```
views:
  - theme: Backend-selected
    title: Home
    type: custom:grid-layout
    layout:
      gridrows: auto
      grid-template-columns: 25% 12.5% 25% 12.5% 25%
      grid-template-areas: |
        "a b c d e"
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: picture
            image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
            tap_action:
              action: none
            hold_action:
              action: none
          - type: picture
            image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
            tap_action:
              action: none
            hold_action:
              action: none
        view_layout:
          grid-area: a
      - type: vertical-stack
        cards:
          - type: picture
            image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
            tap_action:
              action: none
            hold_action:
              action: none
          - type: picture
            image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
            tap_action:
              action: none
            hold_action:
              action: none
        view_layout:
          grid-area: e
      - type: custom:meteoalarm-card
        entities:
          entity: binary_sensor.meteoalarm
        integration: meteoalarm
        view_layout:
          grid-area: c
```


I also noticed that adding this custom css to the alert card with [card-mod](https://github.com/thomasloven/lovelace-card-mod) seems to fix it, at least partially. Haven't tested how it behaves with alerts as we currently don't have any, but with this the card only takes the space it needs.
```
style: |
  :host {
    flex: 0 !important;
  }
```

Full example of the card with the css:
```
type: custom:meteoalarm-card
entities:
  entity: binary_sensor.meteoalarm
integration: meteoalarm
view_layout:
  grid-area: c
style: |
  :host {
    flex: 0 !important;
  }
```

**Comment by Aasikki** [comment]
> I really don't know how to proceed here. Any other card actually does stretch to full height here, like the current implementation of MeteoalarmCard but the content is sometimes centred sometimes not. While your request is about not stretching it at all with is just not consistent

Hmm, well that's interesting. I quess I never thought to try it like that without adding the card in a vertical stack.
If I replace the center card with a vertical stack and add the alert card + other cards, then the only card whitch becomes full height is the alert card.
![image](https://user-images.githubusercontent.com/58399890/229096884-7a288788-5fb1-49c1-b9bc-60f98e8f7c8e.png)

This is the vertical stack card I used in that screenshot
```
type: vertical-stack
cards:
  - type: weather-forecast
    entity: weather.home
  - type: custom:meteoalarm-card
    entities:
      entity: binary_sensor.meteoalarm
    integration: meteoalarm
view_layout:
  grid-area: c
```
