### ISSUE TITLE
Error: Unknown warning: Freeze Watch

### ISSUE THREAD

**Issue by bmcclure** [MrBartusek/MeteoalarmCard#167]
### Describe the bug

I am using the Weatheralerts integration, and there has been a freeze watch in effect for a couple of days which has caused this card to show this error:

`Error: Unknown warning: Freeze Watch`

### Steps to reproduce

1. Add a weatheralerts meteoalarm card
2. Simulate or wait for a Freeze Watch to occur I guess?
3. See the error message

### Card version

2.4.3

### Integration type

weatheralerts

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

```yaml
type: custom:meteoalarm-card
entities:
  - entity: sensor.berkeley
integration: weatheralerts
override_headline: false
scaling_mode: headline_and_scale
hide_when_no_warning: true
view_layout:
  grid-area: header
```

### Integration Configuration

```yaml
sensor:
  - platform: weatheralerts
    state: WV
    zone: 52
    county: 3
```
