### ISSUE TITLE
No translation when using vertical layout-card

### ISSUE THREAD

**Issue by metbril** [MrBartusek/MeteoalarmCard#168]
### Describe the bug

When using a custom vertical [layout-card](https://github.com/thomasloven/lovelace-layout-card), weather alerts are not translated.

Default masonry layout:
<img width="349" alt="Scherm­afbeelding 2023-05-05 om 17 02 36" src="https://user-images.githubusercontent.com/559346/236495835-c80e6f95-0f3a-49fe-ae3e-c9af2757ff14.png">

One of the custom vertical layout:
<img width="461" alt="Scherm­afbeelding 2023-05-05 om 17 03 25" src="https://user-images.githubusercontent.com/559346/236495881-27c503a2-45b2-4bb8-89c3-c2caa5911fb0.png">

### Card version

v2.4.3

### Integration type

Meteoalarm

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

```yaml
type: custom:meteoalarm-card
entities:
  - entity: binary_sensor.meteoalarm_zuid_holland
integration: meteoalarm
hide_when_no_warning: true
scaling_mode: headline_and_scale
override_headline: false
```

### Integration Configuration

```yaml
[PASTE CONFIGURATION HERE]
```
