### ISSUE TITLE
hide_when_no_warning broken?

### ISSUE THREAD

**Issue by CumpsD** [MrBartusek/MeteoalarmCard#180]
### Describe the bug

After upgrading to 2.5.0 it seems `hide_when_no_warning` is broken. I have it enabled, yet it still shows the card even when there are no warnings.

### Screenshots

![image](https://github.com/MrBartusek/MeteoalarmCard/assets/1201644/c6d016d2-2a84-4c43-a28a-c8a609f91d3f)

### Card version

v2.5.0

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

```yaml
type: custom:meteoalarm-card
entities: binary_sensor.meteoalarm
integration: meteoalarm
override_headline: false
hide_when_no_warning: true
tap_action:
  action: url
  url_path: https://www.meteo.be/nl/weer/waarschuwingen/overzichtskaart-belgie
```

### Integration type

Meteoalarm
