### ISSUE TITLE
`hide_when_no_warning` seems not working

### ISSUE THREAD

**Issue by SiriosDev** [MrBartusek/MeteoalarmCard#182]
### Describe the bug

The `hide_when_no_warning` tag set to `true` does not hide the card

### Integration state attributes

```yaml
#basic
attribution: Information provided by MeteoAlarm
device_class: safety
friendly_name: meteoalarm
#wrap
attribution: Information provided by MeteoAlarm
language: null
category: null
event: null
responseType: null
urgency: null
severity: null
certainty: null
effective: null
onset: null
expires: null
senderName: null
headline: null
description: null
Consequences: null
instruction: null
awareness_level: null
awareness_type: null
device_class: safety
icon: mdi:alert-circle
friendly_name: eumeteoalarm
```

### Screenshots

![image](https://github.com/MrBartusek/MeteoalarmCard/assets/26876994/18607633-e844-4a45-8074-7ce110ccacfb)

### Card version

v.2.5.1

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

```yaml
type: custom:meteoalarm-card
integration: meteoalarm
entities:
  - entity: binary_sensor.eumeteoalarm
hide_when_no_warning: true
override_headline: true
scaling_mode: headline_and_scale
```

### Integration type

Meteoalarm

### Integration configuration

YAML (configuration.yaml)

### Integration Configuration

```yaml
binary_sensor:
  - platform: meteoalarm
    language: "it-IT"
    country: "italy"
    province: "Calabria"

#"full-wrapped" (basically nothing changes) with

template:
  - binary_sensor:
      - name: "eumeteoalarm"
        unique_id: 3d518df7-6cad-44b6-bfdf-55fec1ba0f83
        icon: mdi:alert-circle
        device_class: "safety"
        state: >
          {{ states('binary_sensor.meteoalarm') }}
        attributes:
          attribution: >
            {{ state_attr("binary_sensor.meteoalarm", "attribution") }}
          language: >
            {{ state_attr("binary_sensor.meteoalarm", "language") }}
          category: >
            {{ state_attr("binary_sensor.meteoalarm", "category") }}
          event: >
            {{ state_attr("binary_sensor.meteoalarm", "event") }}
          responseType: >
            {{ state_attr("binary_sensor.meteoalarm", "responseType") }}
          urgency: >
            {{ state_attr("binary_sensor.meteoalarm", "urgency") }}
          severity: >
            {{ state_attr("binary_sensor.meteoalarm", "severity") }}
          certainty: >
            {{ state_attr("binary_sensor.meteoalarm", "certainty") }}
          effective: >
            {{ state_attr("binary_sensor.meteoalarm", "effective") }}
          onset: >
            {{ state_attr("binary_sensor.meteoalarm", "onset") }}
          expires: >
            {{ state_attr("binary_sensor.meteoalarm", "expires") }}
          senderName: >
            {{ state_attr("binary_sensor.meteoalarm", "senderName") }}
          headline: >
            {{ state_attr("binary_sensor.meteoalarm", "headline") }}
          description: >
            {{ state_attr("binary_sensor.meteoalarm", "description") }}
          Consequences: >
            {{ state_attr("binary_sensor.meteoalarm", "Consequences") }}
          instruction: >
            {{ state_attr("binary_sensor.meteoalarm", "instruction") }}
          awareness_level: >
            {{ state_attr("binary_sensor.meteoalarm", "awareness_level") }}
          awareness_type: >
            {{ state_attr("binary_sensor.meteoalarm", "awareness_type") }}
```
