### ISSUE TITLE
event filter doesn't work with DWD

### ISSUE THREAD

**Issue by jzielke84** [MrBartusek/MeteoalarmCard#191]
### Describe the bug

The feature mentioned in https://github.com/MrBartusek/MeteoalarmCard/pull/176 doesn't work with DWD.

### Integration state attributes
```yaml
region_name: Köln-Kalk
region_id: 705315108
last_update: 2023-06-19T12:34:15.579000+00:00
warning_count: 1
warning_1_name: STARKE HITZE
warning_1_type: 247
warning_1_level: 1
warning_1_headline: Amtliche WARNUNG vor HITZE
warning_1_description: Am Dienstag wird eine starke Wärmebelastung erwartet. Dienstag ist mit einer zusätzlichen Belastung aufgrund verringerter nächtlicher Abkühlung insbesondere im dicht bebauten Stadtgebiet von Köln zu rechnen. 
warning_1_instruction: Hitzebelastung kann für den menschlichen Körper gefährlich werden und zu einer Vielzahl von gesundheitlichen Problemen führen. Vermeiden Sie nach Möglichkeit die Hitze, trinken Sie ausreichend Wasser und halten Sie die Innenräume kühl.
warning_1_start: 2023-06-20T09:00:00+00:00
warning_1_end: 2023-06-20T17:00:00+00:00
warning_1_parameters: null
warning_1_color: #cc99ff
warning_1: 
start_time: '2023-06-20T09:00:00+00:00'
end_time: '2023-06-20T17:00:00+00:00'
event: STARKE HITZE
event_code: 247
headline: Amtliche WARNUNG vor HITZE
description: >-
  Am Dienstag wird eine starke Wärmebelastung erwartet. Dienstag ist mit einer
  zusätzlichen Belastung aufgrund verringerter nächtlicher Abkühlung
  insbesondere im dicht bebauten Stadtgebiet von Köln zu rechnen. 
instruction: >-
  Hitzebelastung kann für den menschlichen Körper gefährlich werden und zu einer
  Vielzahl von gesundheitlichen Problemen führen. Vermeiden Sie nach Möglichkeit
  die Hitze, trinken Sie ausreichend Wasser und halten Sie die Innenräume kühl.
urgency: immediate
level: 1
parameters: null
color: '#cc99ff'

attribution: Data provided by DWD
icon: mdi:close-octagon-outline
friendly_name: DWD Weather Warnings 705315108 Current Warning Level
```
### Screenshots

![image](https://github.com/MrBartusek/MeteoalarmCard/assets/13448042/7325e2a5-ca49-41ab-8205-9fd8308441c7)

### Card version

2.5.2

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration
```yaml
type: custom:meteoalarm-card
integration: dwd
entities:
  - entity: sensor.dwd_weather_warnings_705315108_current_warning_level
hide_caption: false
hide_when_no_warning: true
override_headline: true
scaling_mode: headline
ignored_events:
  - STARKE HITZE
style: |
  .content {
    padding: 8px !important;
  }
  .swiper-slide-active {
    animation: blinker 2s linear infinite !important;
  }
  @keyframes blinker {
    50% {
      opacity: 0;
    }
  }
```
### Integration type

Meteoalarm

### Integration configuration

YAML (configuration.yaml)

### Integration Configuration

Inside HA since this has been changed in the latest version. It now looks like this:
![image](https://github.com/MrBartusek/MeteoalarmCard/assets/13448042/f7df6213-e3c8-4d1f-ae82-c49d25b114bd)
