### ISSUE TITLE
Filter for headline text

### ISSUE THREAD

**Issue by jzielke84** [MrBartusek/MeteoalarmCard#210]
Some warning provided by Nina (like a local flooding warning) are shown as "Unkown event", making it impossible to filter. Hence I request an additional functionality to hide the card, when a certain Headline (e.g. "Hochwasserinformation") shows up.

**Comment by MrBartusek** [comment]
It will be quite hard to implement, open to ideas

> This might be related to lack of data by the Nina API

It is

**Comment by jzielke84** [comment]
It's a bit of a dirty hack:

```yaml
  type: entity-filter
  state_filter:
    - operator: "!="
      value: "Hochwasserinformation"
      attribute: headline
  entities:
    - binary_sensor.warning_koln_stadt_1

  card:
    type: custom:meteoalarm-card
    entity: update.home_assistant_supervisor_update
    integration: nina
    entities:
      - entity: binary_sensor.warning_koln_stadt_1
    disable_swiper: false
    hide_caption: false
    hide_when_no_warning: true
    override_headline: false
    scaling_mode: scale
    ignored_events:
      - Flooding
      - Rain
      - Avalanches
    style: |
      .content {
        padding: 8px !important;
      }
    tap_action:
      action: navigate
      navigation_path: /lovelace/katwarn
```

Repeat the card for each binary_sensor.
