### ISSUE TITLE
Add font-size in card styles

### ISSUE THREAD

**Issue by duczz** [MrBartusek/MeteoalarmCard#231]
it would be nice when i can set the font size in the card via styles

**Comment by MrBartusek** [comment]
Thank you for the idea :heart: This will be a part of `v2.7.0`

```yaml
type: custom:meteoalarm-card
entities:
  - entity: sensor.32_weather_alert
integration: meteofrance
scaling_mode: disabled
card_mod:
  style: |
    ha-card {
      --headline-font-size: 12px;
    }
```
