### ISSUE TITLE
Unknown weatheralerts alert type: Air Stagnation

### ISSUE THREAD

**Issue by MrBartusek** [MrBartusek/MeteoalarmCard#233]
### Describe the bug

`Air Stagnation` event is not detected

### Integration state attributes

```yaml
alerts:
  - area: >-
      Kootenai/Cabinet Region; West Glacier Region; Flathead/Mission Valleys;
      Lower Clark Fork Region; Missoula/Bitterroot Valleys; Bitterroot/Sapphire
      Mountains; Potomac/Seeley Lake Region
    certainty: Likely
    description: |-
      * WHAT...Stagnant conditions will trap pollutants, leading to
      deteriorating air quality.

      * WHERE...Flathead/Mission Valleys, Kootenai/Cabinet Region, West
      Glacier Region, Bitterroot/Sapphire Mountains, Lower Clark Fork
      Region, Missoula/Bitterroot Valleys, and Potomac/Seeley Lake
      Region.

      * WHEN...Until 11 PM MST Monday.

      * IMPACTS...Periods of air stagnation can lead to the build up of
      pollutants near the surface.
    ends: "2023-12-18T23:00:00-07:00"
    event: Air Stagnation Advisory
    instruction: |-
      Persons with respiratory illness should follow their physicians
      advice for dealing with high levels of air pollution during periods
      of stagnant air.

      According to state air quality agencies, prolonged period of
      stagnant air can hold pollutants close to the ground where people
      live and breathe. Check with your local burn agency for any current
      restrictions in your area. For more information on air quality in
      Montana, visit website www.deq.mt.gov/air
    response: Execute
    sent: "2023-12-17T07:29:00-07:00"
    severity: Moderate
    title: >-
      Air Stagnation Advisory issued December 17 at 7:29AM MST until December 18
      at 11:00PM MST
    urgency: Expected
    NWSheadline:
      - AIR STAGNATION ADVISORY REMAINS IN EFFECT UNTIL 11 PM MST MONDAY
    hailSize: "null"
    windGust: "null"
    waterspoutDetection: "null"
    effective: "2023-12-17T07:29:00-07:00"
    expires: "2023-12-18T23:00:00-07:00"
    endsExpires: "2023-12-18T23:00:00-07:00"
    onset: "2023-12-17T07:29:00-07:00"
    status: Actual
    messageType: Update
    category: Met
    sender: w-nws.webmaster@noaa.gov
    senderName: NWS Missoula MT
    id: urn:oid:2.49.0.1.840.0.d263a7122e58d425295d06dc13bf22ea51d72b03.002.1
    zoneid: MTZ005,MTC063
integration: weatheralerts
state: MT
zone: MTZ005,MTC063
unit_of_measurement: Alerts
icon: mdi:alert-octagram
friendly_name: Missoula/Bitterroot Valleys
```

### Screenshots

![image](https://github.com/MrBartusek/MeteoalarmCard/assets/23432278/5a7a2401-505b-46f4-8e92-9799d657d773)

### Card version

2.6.0

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

```yaml
type: custom:meteoalarm-card
entities:
  - entity: sensor.missoula_bitterroot_valleys
integration: weatheralerts
```

### Integration type

weatheralerts

### Integration configuration

GUI
