### ISSUE TITLE
Unknown event type: Coastalevent

### ISSUE THREAD

**Issue by metbril** [MrBartusek/MeteoalarmCard#234]
### Describe the bug

The coastal event (high water warning) is not (yet) recognized.

**state attributes:**
```yaml
language: nl-NL
category: Met
event: awareness_type=07,awareness_level=3.0
responseType: Monitor
urgency: Future
severity: Severe
certainty: Likely
effective: "2023-12-21T10:21:00+00:00"
onset: "2023-12-21T16:00:00+00:00"
expires: "2023-12-22T04:59:59+00:00"
senderName: Rijkswaterstaat
headline: Coastalevent - Waarschuwingen voor Zuid-Holland - Nederland
description: >-
  De verwachte waterstanden in de sector komen boven het alarmpeil
  (herhalingstijd eens per 5 jaar). Buitendijkse gebieden lopen onder en de
  meeste coupures en stormvloedkeringen zullen gesloten worden. In de sector
  wordt dijkbewaking ingesteld.
instruction: >-
  Meer informatie:
  https://www.rijkswaterstaat.nl/water/waterdata-en-waterberichtgeving/waterbericht/index.aspx
web: http://meteoalarm.eu/nl-NL/0/0/NL009-Zuid-Holland.html
contact: wmcn-waterkamer@rws.nl
awareness_type: 7; coastalevent
awareness_level: 3; orange; Severe
attribution: Information provided by MeteoAlarm
device_class: safety
friendly_name: Meteoalarm Zuid-Holland

```

### Screenshots

![image](https://github.com/MrBartusek/MeteoalarmCard/assets/559346/04e6ccee-9d16-4026-bbc3-790ede38077e)
![image](https://github.com/MrBartusek/MeteoalarmCard/assets/559346/1caafcd7-e4cb-4b6e-a95e-c09b704f42b3)

### Card version

v2.6.0

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

type: custom:meteoalarm-card
entities:
  - entity: binary_sensor.meteoalarm_zuid_holland
integration: meteoalarm
hide_when_no_warning: true
scaling_mode: headline_and_scale
override_headline: false

### Integration type

Meteoalarm

### Integration configuration

YAML (configuration.yaml)

### Integration Configuration

- platform: meteoalarm
  name: Meteoalarm Zuid-Holland
  country: 'netherlands'
  province: 'Zuid-Holland'
  language: 'nl-NL'
