### ISSUE TITLE
Unknown event ID: 86

### ISSUE THREAD

**Issue by niklas1375** [MrBartusek/MeteoalarmCard#239]
### Describe the bug

The German DWD issued a warning of extreme freezing rain with the code 86 which doesn't seem to be recognized by the meteo card as it displays an error message saying that event ID 86 is unkown. I attached a screenshot and the state (removed other warnings) of the entity.

### Integration state attributes
```yaml
region_name: xxxxxxxxx
region_id: xxxxxxxxx
last_update: 2024-01-16T18:40:44.829000+00:00

# excluded warning 1 and 2 since they were not relevant 

warning_3_name: EXTREMES GLATTEIS
warning_3_type: 86
warning_3_level: 4
warning_3_headline: Amtliche UNWETTERWARNUNG vor EXTREMEM GLATTEIS
warning_3_description: Es besteht sehr hohe Glatteisgefahr durch gefrierenden Regen sowie starken Eisansatz.
warning_3_instruction: Große Gefahr für Leib und Leben durch gefrierenden Regen mit starkem Eisansatz; verbreiteten Eisbruch. 
Handlungsempfehlungen: 
Aufenthalt im Freien und Fahrten unbedingt vermeiden; auf erhebliche Beeinträchtigungen auf allen Verkehrswegen bis hin zu Sperrungen/Schließungen einstellen, notfalls Fahrweise anpassen, möglichst volltanken, Decken und warme Getränke mitführen; auf Netzausfälle vorbereiten (z.B. Strom, Mobilfunk, ...); die Entwicklung der Gefährdungslage in Radio, Fernsehen, Internet etc. verfolgen; Aufforderungen der Katastrophenschutz-/Zivilschutzbehörden folgen
warning_3_start: 2024-01-17T05:00:00+00:00
warning_3_end: 2024-01-18T03:00:00+00:00
warning_3_parameters: 
Ursache: freezing rain

warning_3_color: #880e4f
warning_3: 
start_time: '2024-01-17T05:00:00+00:00'
end_time: '2024-01-18T03:00:00+00:00'
event: EXTREMES GLATTEIS
event_code: 86
headline: Amtliche UNWETTERWARNUNG vor EXTREMEM GLATTEIS
description: >-
  Es besteht sehr hohe Glatteisgefahr durch gefrierenden Regen sowie starken
  Eisansatz.
instruction: >-
  Große Gefahr für Leib und Leben durch gefrierenden Regen mit starkem
  Eisansatz; verbreiteten Eisbruch. 

  Handlungsempfehlungen: 

  Aufenthalt im Freien und Fahrten unbedingt vermeiden; auf erhebliche
  Beeinträchtigungen auf allen Verkehrswegen bis hin zu Sperrungen/Schließungen
  einstellen, notfalls Fahrweise anpassen, möglichst volltanken, Decken und
  warme Getränke mitführen; auf Netzausfälle vorbereiten (z.B. Strom, Mobilfunk,
  ...); die Entwicklung der Gefährdungslage in Radio, Fernsehen, Internet etc.
  verfolgen; Aufforderungen der Katastrophenschutz-/Zivilschutzbehörden folgen
urgency: immediate
level: 4
parameters:
  Ursache: freezing rain
color: '#880e4f'

attribution: Data provided by DWD
icon: mdi:close-octagon-outline
friendly_name: DWD Weather Warnings xxxxxxxxxx Aktuelle Warnstufe
```

### Screenshots

![image](https://github.com/MrBartusek/MeteoalarmCard/assets/8780196/00f4a8ec-e32c-41dd-a7e9-e5b340e6d378)

### Card version

v2.6.0

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

```yaml
type: custom:meteoalarm-card
entities:
  - entity: sensor.dwd_weather_warnings_xxxxxxxxxx_current_warning_level
  - entity: sensor.dwd_weather_warnings_xxxxxxxxxx_advance_warning_level
integration: dwd
```

### Integration type

Deutscher Wetterdienst (DWD)

### Integration configuration

GUI
