### ISSUE TITLE
Card won't be shown when a warning is active

### ISSUE THREAD

**Issue by ChristophCaina** [MrBartusek/MeteoalarmCard#265]
### Describe the bug

I am using the Card with NINA and with DWD Warnings.
I had a warning from DWD - but instead of the warning, only a grey bar was rendered.

Now, the warning is gone and the card is visible again (with no warnings)...

red is the NINA sensor - without warnings, blue the one from DWD with an active warning at that time (see screenshot)

### Screenshots

![image](https://github.com/MrBartusek/MeteoalarmCard/assets/26391061/53a4105c-944d-44a6-abb4-1c83cdd05ad9)

### Card version

v2.7.1

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

```
type: custom:meteoalarm-card
integration: dwd
entities:
  - entity: sensor.kreis_boblingen_vorwarnstufe
  - entity: sensor.kreis_boblingen_aktuelle_warnstufe
override_headline: true
disable_swiper: true
hide_caption: true
hide_when_no_warning: false
scaling_mode: headline_and_scale
```

### Integration type

Deutscher Wetterdienst (DWD)

### Integration configuration

GUI
