### ISSUE TITLE
"High Temperature" filter doesn't work for DWD

### ISSUE THREAD

**Issue by jzielke84** [MrBartusek/MeteoalarmCard#268]
Reagrding to https://github.com/MrBartusek/MeteoalarmCard/pull/211 the ignore filter "High Temperature" doesn't seem to work.

Data provided:

```
region_name: Köln-Kalk
region_id: 705315108
last_update: 2024-08-12T08:03:26.377000+00:00
warning_count: 2
warning_1_name: STARKE HITZE
warning_1_type: 247
warning_1_level: 1
warning_1_headline: Amtliche WARNUNG vor HITZE
warning_1_description: 
Am Montag wird eine starke Wärmebelastung erwartet.
Mit einer zusätzlichen Belastung aufgrund verringerter nächtlicher Abkühlung ist insbesondere im dicht bebauten Stadtgebiet von Köln zu rechnen.
Am Dienstag wird eine starke Wärmebelastung erwartet.
Die Hitze wird alte und pflegebedürftige Menschen extrem belasten. Mit einer zusätzlichen Belastung aufgrund verringerter nächtlicher Abkühlung ist insbesondere im dicht bebauten Stadtgebiet von Köln zu rechnen.

warning_1_instruction: Hitzebelastung kann für den menschlichen Körper gefährlich werden und zu einer Vielzahl von gesundheitlichen Problemen führen. Vermeiden Sie nach Möglichkeit die Hitze, trinken Sie ausreichend Wasser und halten Sie die Innenräume kühl.
warning_1_start: 2024-08-12T09:00:00+00:00
warning_1_end: 2024-08-13T09:00:00+00:00
warning_1_parameters: null
warning_1_color: #cc99ff
warning_1: 
start_time: '2024-08-12T09:00:00+00:00'
end_time: '2024-08-13T09:00:00+00:00'
event: STARKE HITZE
event_code: 247
headline: Amtliche WARNUNG vor HITZE
description: >

  Am Montag wird eine starke Wärmebelastung erwartet.

  Mit einer zusätzlichen Belastung aufgrund verringerter nächtlicher Abkühlung
  ist insbesondere im dicht bebauten Stadtgebiet von Köln zu rechnen.

  Am Dienstag wird eine starke Wärmebelastung erwartet.

  Die Hitze wird alte und pflegebedürftige Menschen extrem belasten. Mit einer
  zusätzlichen Belastung aufgrund verringerter nächtlicher Abkühlung ist
  insbesondere im dicht bebauten Stadtgebiet von Köln zu rechnen.
instruction: >-
  Hitzebelastung kann für den menschlichen Körper gefährlich werden und zu einer
  Vielzahl von gesundheitlichen Problemen führen. Vermeiden Sie nach Möglichkeit
  die Hitze, trinken Sie ausreichend Wasser und halten Sie die Innenräume kühl.
urgency: immediate
level: 1
parameters: null
color: '#cc99ff'

warning_2_name: EXTREME HITZE
warning_2_type: 248
warning_2_level: 3
warning_2_headline: Amtliche WARNUNG vor extremer HITZE
warning_2_description: 
Am Dienstag wird eine extreme Wärmebelastung erwartet.
Mit einer zusätzlichen Belastung aufgrund verringerter nächtlicher Abkühlung ist insbesondere im dicht bebauten Stadtgebiet von Köln zu rechnen.

warning_2_instruction: Hitzebelastung kann für den menschlichen Körper gefährlich werden und zu einer Vielzahl von gesundheitlichen Problemen führen. Vermeiden Sie nach Möglichkeit die Hitze, trinken Sie ausreichend Wasser und halten Sie die Innenräume kühl.
warning_2_start: 2024-08-13T09:00:00+00:00
warning_2_end: 2024-08-13T17:00:00+00:00
warning_2_parameters: null
warning_2_color: #9e46f8
warning_2: 
start_time: '2024-08-13T09:00:00+00:00'
end_time: '2024-08-13T17:00:00+00:00'
event: EXTREME HITZE
event_code: 248
headline: Amtliche WARNUNG vor extremer HITZE
description: >

  Am Dienstag wird eine extreme Wärmebelastung erwartet.

  Mit einer zusätzlichen Belastung aufgrund verringerter nächtlicher Abkühlung
  ist insbesondere im dicht bebauten Stadtgebiet von Köln zu rechnen.
instruction: >-
  Hitzebelastung kann für den menschlichen Körper gefährlich werden und zu einer
  Vielzahl von gesundheitlichen Problemen führen. Vermeiden Sie nach Möglichkeit
  die Hitze, trinken Sie ausreichend Wasser und halten Sie die Innenräume kühl.
urgency: immediate
level: 3
parameters: null
color: '#9e46f8'

attribution: Data provided by DWD
friendly_name: Köln-Kalk Current warning level
```

card config:

```yaml

type: custom:meteoalarm-card
integration: dwd
entities:
  - entity: sensor.koln_kalk_current_warning_level
hide_caption: true
hide_when_no_warning: true
override_headline: true
scaling_mode: headline
ignored_events:
  - High Temperature
  - Low Temperature
  - Snow/Ice
  - Fog
  - Flodding
disable_swiper: false
tap_action:
  action: navigate
  navigation_path: /lovelace/katwarn
card_mod:
  style: |
    .content {
      padding: 8px !important;
    }
    .swiper-slide-active {
      animation: blinker 2s linear infinite !important;
    }
    @keyframes blinker {
      50% {
        opacity: 0;
      }
    }
```
