### ISSUE TITLE
Add Option to Set Card Height in Configuration

### ISSUE THREAD

**Issue by BlueheIix** [MrBartusek/MeteoalarmCard#274]
**Problem Description**
Currently, I am facing difficulties in adjusting the height of the Card. There doesn't seem to be an option to set the height directly, and attempts to use [card-mod](https://github.com/thomasloven/lovelace-card-mod) for this purpose have resulted in misaligned content, particularly with vertical text alignment. A simple way to change the card height would make it much easier to integrate it into custom dashboards and maintain a consistent visual appearance.

**Proposed Solution**
I suggest adding a configuration option to adjust the card height directly. For example, an attribute like 
```
type: custom:meteoalarm-card
entity: sensor.meteoalarm
height: 300px  # Example to set card height
```
could be added to the card settings. This would provide a straightforward way to control the height, without needing complex CSS workarounds that might not always work as expected.

Thank you very much for considering this request!

**Comment by MrBartusek** [comment]
Hey! The proper way to do this kind of modification would be `card-mod`. We won't add that kind of styling changes. Here is an example that you can try. Let me know if that fixes the issue

```yaml
type: custom:meteoalarm-card
entities:
  - entity: binary_sensor.meteoalarm
integration: meteoalarm
card_mod:
  style: |
    .content {
      padding: 12px 18px !important;
    }
```
![image](https://github.com/user-attachments/assets/6e24f206-2e30-4ae5-8377-aad92c3aad29)
