### ISSUE TITLE
Card click action

### ISSUE THREAD

**Issue by bmengineer-gear** [MrBartusek/MeteoalarmCard#285]
**Is your feature request related to a problem? Please describe.**
No, feature request.

**Describe the solution you'd like**
Currently, clicking on the card takes you to the entity history.
I'd like to remap this so clicking can take me to the weather provider's website for more information about the current warning or alert

**Additional context**

**Comment by MrBartusek** [comment]
You can use [Actions](https://www.home-assistant.io/dashboards/actions/) syntax:
```yaml
type: custom:meteoalarm-card
entities:
  - entity: binary_sensor.meteoalarm
integration: meteoalarm
tap_action:
  action: url
  url_path: https://meteoalarm.org/en/live/
```
