### ISSUE TITLE
Environment Canada - Air Quality Warning

### ISSUE THREAD

**Issue by SirMaple** [MrBartusek/MeteoalarmCard#286]
### Describe the bug

Thank you for creating this great Integration. I've been using it for a year now and haven't had any issues with it. Until now.

With wildfire smoke comes the Air Quality Warnings. It appears that this card doesn't like this. It displays the following:

```
Error: Unknown Environnement Canada alert encountered! Name: Air Quality Warning (isFrench=false)

name: Meteoalarm
type: custom:meteoalarm-card
entities:
  - entity: sensor.calgary_advisory
  - entity: sensor.calgary_warnings
  - entity: sensor.calgary_watches
  - entity: sensor.calgary_statements
integration: env_canada
hide_when_no_warning: true
scaling_mode: headline_and_scale
tap_action:
  action: url
  url_path: https://weather.gc.ca/en/location/index.html?coords=51.046,-114.057
```

### Integration state attributes

`sensor.calgary_warnings` shows

State as 1

And attributes:
```
location: Calgary
station: Calgary Int'l Airport
alert_1: Air Quality Warning
alert_time_1: Wednesday June 11, 2025 at 04:05 MDT
attribution: Data provided by Environment Canada
friendly_name: Calgary Warnings
```

### Screenshots

Firefox Console Error:
```
[METEOALARM CARD ERROR]
Report issue: https://bit.ly/3hK1hL4 

 Error: Unknown Environnement Canada alert encountered! Name: Air Quality Warning (isFrench=false)
    getAlerts https://home.mydomain.ca/hacsfiles/MeteoalarmCard/meteoalarm-card.js?hacstag=361205663272:694
    graterAllAlerts https://home.mydomain.ca/hacsfiles/MeteoalarmCard/meteoalarm-card.js?hacstag=361205663272:76
    getEvents https://home.mydomain.ca/hacsfiles/MeteoalarmCard/meteoalarm-card.js?hacstag=361205663272:76
    render https://home.mydomain.ca/hacsfiles/MeteoalarmCard/meteoalarm-card.js?hacstag=361205663272:818
    update https://home.mydomain.ca/hacsfiles/MeteoalarmCard/meteoalarm-card.js?hacstag=361205663272:24
    performUpdate https://home.mydomain.ca/hacsfiles/MeteoalarmCard/meteoalarm-card.js?hacstag=361205663272:12
    scheduleUpdate https://home.mydomain.ca/hacsfiles/MeteoalarmCard/meteoalarm-card.js?hacstag=361205663272:12
    _$E_ https://home.mydomain.ca/hacsfiles/MeteoalarmCard/meteoalarm-card.js?hacstag=361205663272:12
meteoalarm-card.js:850:31
    render https://home.mydomain.ca/hacsfiles/MeteoalarmCard/meteoalarm-card.js?hacstag=361205663272:850
    update https://home.mydomain.ca/hacsfiles/MeteoalarmCard/meteoalarm-card.js?hacstag=361205663272:24
    performUpdate https://home.mydomain.ca/hacsfiles/MeteoalarmCard/meteoalarm-card.js?hacstag=361205663272:12
    scheduleUpdate https://home.mydomain.ca/hacsfiles/MeteoalarmCard/meteoalarm-card.js?hacstag=361205663272:12
    _$E_ https://home.mydomain.ca/hacsfiles/MeteoalarmCard/meteoalarm-card.js?hacstag=361205663272:12
```
Screenshot of the card in HA Dashboard
![Image](https://github.com/user-attachments/assets/20cbd0a9-736b-4520-a6fe-874dc5f8bf94)

### Card version

v2.7.2

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration
```
type: custom:meteoalarm-card
entities:
  - entity: sensor.calgary_advisory
  - entity: sensor.calgary_warnings
  - entity: sensor.calgary_watches
  - entity: sensor.calgary_statements
integration: env_canada
hide_when_no_warning: true
scaling_mode: headline_and_scale
tap_action:
  action: url
  url_path: https://weather.gc.ca/en/location/index.html?coords=51.046,-114.057
```
### Integration type

Environnement Canada

### Integration configuration

GUI
