### ISSUE TITLE
`hide_when_no_warning` hides all cards even when only one is hidden

### ISSUE THREAD

**Issue by RubenKelevra** [MrBartusek/MeteoalarmCard#68]
**Describe the bug**

I have the following view configured:

```
title: Rooms
views:
  - title: Outdoor
    path: outdoor
    cards:
      - type: custom:meteoalarm-card
        entity: sensor.dwd_weather_warnings_current_warning_level
        hide_when_no_warning: true
        integration: dwd
      - type: custom:meteoalarm-card
        entity: sensor.dwd_weather_warnings_advance_warning_level
        hide_when_no_warning: true
        integration: dwd
```

If the advance_warning is empty, the current warning won't be shown as well. Even if I have `hide_when_no_warning: false` on the current warning.

**Expected behavior**
Only the empty warning display should be removed OR they should only be removed if both are empty.

**System (please complete the following information):**
 - Card version: No idea where to find this info.
 - Integration type: DWD
 - Installation type: HACS
